In [2]:
#Char to num
cipher = "etsd"
cipher.lower()
cipher = list(cipher)
for i in range(len(cipher)):
    cipher[i] = ord(cipher[i])-97
print(cipher)
'''
15 17  0]
[24  5 14]
[17 18 13]
[14 22 25]
'''

[4, 19, 18, 3]


'\n15 17  0]\n[24  5 14]\n[17 18 13]\n[14 22 25]\n'

In [30]:
#Num to char
num = [21, 22]
for i in num:
    print(chr(i+97), end="")

vw

In [16]:
def convert_to_base(n, base):
    rem = []
    while n != 0:
        quotient = floor(n/base)
        
        rem.append(n-quotient*base)
        n = quotient
    rem.reverse()
    print(rem)
    

convert_to_base(7, 2)



[1, 1, 1]


In [2]:
n = 82

print(floor(n/2), n-floor(n/2)*2)
657.str(2)


41 0


'1010010001'

In [26]:
n = 95
modu = 126
s = 24
for i in range(100):
    if (i*n)%modu == 1:
        print(i,(i*n)%modu, "** HERE! **")
        k = i
        break
    print(i,(i*n)%modu)

0 0
1 95
2 64
3 33
4 2
5 97
6 66
7 35
8 4
9 99
10 68
11 37
12 6
13 101
14 70
15 39
16 8
17 103
18 72
19 41
20 10
21 105
22 74
23 43
24 12
25 107
26 76
27 45
28 14
29 109
30 78
31 47
32 16
33 111
34 80
35 49
36 18
37 113
38 82
39 51
40 20
41 115
42 84
43 53
44 22
45 117
46 86
47 55
48 24
49 119
50 88
51 57
52 26
53 121
54 90
55 59
56 28
57 123
58 92
59 61
60 30
61 125
62 94
63 63
64 32
65 1 ** HERE! **


In [6]:
modu = modu
k = k
s = s
cipher = "RN"
cipher = cipher.lower()
cipher = list(cipher)
print(cipher)
for i in range(len(cipher)):
    cipher[i] = ord(cipher[i])-97
print(cipher)
res = []
for c in cipher:
    print((k*(c-s)%modu, chr(((k*(c-s)) % modu) + 97)))

['r', 'n']
[17, 13]
(25, 'z')
(17, 'r')


In [3]:
## Enter in encryption matrix and message to get encrypted message and decryption matrix

# User Input HERE 
cipher = [6,10,23,17] # Message to be encoded/decoded. Enter in either the string or the list of numbers
start_max = [10,7,3,5] # Enter matrix in sequentially tl to br
modu = 26 # Enter what the modulus you are working in


# Code
enc_max = [] # Encoding matrix. Built from user input e
dec_max = [] # Decoding matrix. Built from inverse of enc_max
mes_max = [] # Message matrix. Resulting matrix containing encoded/decoded results
temp = [] # Used to build encoding and decoding matracies
deg = sqrt(len(start_max)) # "Degree" of matrix. A 3x3 matrix will return 3

#Convert array to matrix
for row in range(0, deg):
    temp = []
    for col in range(deg):
        temp.append(start_max[deg*row+col])
    enc_max.append(temp)
print("Encryption matrix:", enc_max)

#Convert alpha to nums
try: 
    cipher.lower()
    cipher = list(cipher)
    for i in range(len(cipher)):
        cipher[i] = ord(cipher[i])-97
except:
    pass
# Build message matrix
for row in range(len(cipher)/deg):
    temp = []
    for col in range(deg):
        temp.append(cipher[deg*row+col])
    mes_max.append(temp)
    
print("Message matrix", mes_max)
        
print()
print("Decryption matrix:")
dec_max = matrix(IntegerModRing(modu), enc_max)^(-1)
print(dec_max)
print()

print("Encrypted Message")
e=matrix(IntegerModRing(modu), enc_max)
c=matrix(IntegerModRing(modu),mes_max)

print(c*e)
print()
print("Decrypted Message", dec_max)
d=matrix(IntegerModRing(modu), dec_max)

print(c*d)

# Extract the encrypted message matrix as a list
encrypted_list = [num for row in (c * e) for num in row]
print("Encrypted Message (Note if decryption matrix is entered, this will be the decryption)")
print(encrypted_list)
for i in encrypted_list:
    print(chr(int(i)+97), end="")

print("\n")
# Extract the decrypted message matrix as a list
decrypted_list = [num for row in (c * d) for num in row]
print("Decrypted Message (Note if decryption matrix is entered, this will be garbage)")
print(decrypted_list)
for i in decrypted_list:
    print(chr(int(i)+97), end="")


Encryption matrix: [[10, 7], [3, 5]]
Message matrix [[6, 10], [23, 17]]

Decryption matrix:
[19 15]
[25 12]

Encrypted Message
[12 14]
[21 12]

Decrypted Message [19 15]
[25 12]
[0 2]
[4 3]
Encrypted Message (Note if decryption matrix is entered, this will be the decryption)
[12, 14, 21, 12]
movm

Decrypted Message (Note if decryption matrix is entered, this will be garbage)
[0, 2, 4, 3]
aced

In [28]:
import pandas as pd
#import numpy
import time
# Brute force block cipher breaker(2x2)!
def block(matri):
    ## Enter in encryption matrix and message to get encrypted message and decryption matrix
    # User Input HERE 
    cipher = "NARTPXRH" # Message to be encoded/decoded. Enter in either the string or the list of numbers
    start_max = matri # Enter matrix in sequentially tl to br
    modu = 26 # Enter what the modulus you are working in

    # Code
    enc_max = [] # Encoding matrix. Built from user input e
    dec_max = [] # Decoding matrix. Built from inverse of enc_max
    mes_max = [] # Message matrix. Resulting matrix containing encoded/decoded results
    temp = [] # Used to build encoding and decoding matracies
    deg = sqrt(len(start_max)) # "Degree" of matrix. A 3x3 matrix will return 3

    #Convert array to matrix
    for row in range(0, deg):
        temp = []
        for col in range(deg):
            temp.append(start_max[deg*row+col])
        enc_max.append(temp)
    #print("Encryption matrix:", enc_max)

    #Convert alpha to nums
    try: 
        cipher.lower()
        cipher = list(cipher)
        for i in range(len(cipher)):
            cipher[i] = ord(cipher[i])-97
    except:
        pass
    # Build message matrix
    for row in range(len(cipher)/deg):
        temp = []
        for col in range(deg):
            temp.append(cipher[deg*row+col])
        mes_max.append(temp)

    #print("Message matrix", mes_max)

    #print()
    #print("Decryption matrix:")
    dec_max = matrix(IntegerModRing(modu), enc_max)^(-1)
    #print(dec_max)
    #print()

    #print("Encrypted Message")
    e=matrix(IntegerModRing(modu), enc_max)
    c=matrix(IntegerModRing(modu),mes_max)

    #print(c*e)
    #print()
    #print("Decrypted Message", dec_max)
    d=matrix(IntegerModRing(modu), dec_max)

    #print(c*d)

    # Extract the encrypted message matrix as a list
    encrypted_list = [num for row in (c * e) for num in row]
    #print("Encrypted Message (Note if decryption matrix is entered, this will be the decryption)")
    #print(encrypted_list)
    #for i in encrypted_list:
    #    print(chr(int(i)+97), end="")

    #print("\n")
    # Extract the decrypted message matrix as a list
    decrypted_list = [num for row in (c * d) for num in row]
    #print("Decrypted Message (Note if decryption matrix is entered, this will be garbage)")
    #print(decrypted_list)
    output = []
    for i in decrypted_list:
        #print(chr(int(i)+97), end="")
        output.append(chr(int(i)+97))
    return(output)
   
    

# Storage for results
data = []
count = 0
miss = 0

# Try all possible matrices and store successful ones
start = time.time()
for first in range(25):
    for second in range(25):
        for third in range(25):
            for fourth in range(25):
                try:
                    decrypted_text = block([first, second, third, fourth])
                    data.append({
                        "Matrix": f"[{first}, {second}, {third}, {fourth}]",
                        "Decrypted Text": "".join(decrypted_text)
                    })
                    count += 1
                except:
                    miss += 1

print("Successful attempts:", count)
print("Misses due to non-invertible matrices:", miss)
print("In", time.time()-start, "seconds")

df = pd.DataFrame(data)

# Save to CSV file
df.to_csv("brute_force_results.csv", index=False)


ModuleNotFoundError: No module named 'pandas'

In [38]:
gcd(37, 7841)

1

In [39]:
1/883 % 32608

32091

In [44]:
#Char to num (Exponential cipher version!!!)
cipher = "dot"
cipher.lower()
cipher = list(cipher)
for i in range(len(cipher)):
    cipher[i] = ord(cipher[i])-96
print(cipher)


[4, 15, 20]


In [31]:
#Num to char (Exponential cipher version!!!)
num = [22]
for i in num:
    print(chr(i+96), end="")

v

In [53]:
1792548^2283321 % 5023307

100113

In [35]:
def expo_cif(nums, e, p):
    
    d=mod(1/e, p-1)
    print("D:",d)
    for i in nums:
        print("ENC")
        print(i^e % p) #Enc
        print("DEC")
        print(i^d %p) # Dec
expo_cif([18800], 61, 37813)

D: 14257
ENC
13435
DEC
11101


In [9]:
3618^19 % 3911

3856

In [27]:
mod(1/61, 37812.0)

14257

In [69]:
digits = 15
coeff=[1,0,1]
init = [1,1,0]

leng=len(init)
for n in range(leng, digits+1):
    init.append(mod(n*coeff[-1]+ n-1*coeff[-2] + n-2*coeff[-3],2))

print(init)

[1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1]


In [2]:
1/17 % 82

29

In [5]:
82-17*4

14

In [8]:
190/38.0

5.00000000000000

In [1]:
def bad_gcd(first,sec):
    res = 0
    temp = 0
    is_zero=False
    while(not is_zero):
        `
        temp = first % sec
        print(temp)
        if temp != 0:
            res = temp
        else:
            is_zero = True
        first=sec
        sec=temp
bad_gcd(126,95)

31
2
1
0
